### ISSUE TITLE
Add Recycler View to simplify usage

### ISSUE THREAD

**Issue by prashant2018** [prashant2018/ShortRoid#1]
ShortRoid aims to make android development easy by simplifying android codes by creating easy to use wrapper around some boilerplate code. 
Main objective is to do a job only in few lines

Already ShortRoid has three classes:
1. ShortRoidDB - Use SQlLite DB in few lines of code
2. ShortRoidPreference - Shared Preferences in just 2 lines
3 ShortAnimation - Animation of views in one line

**Comment by rrishabhj** [comment]
hey, could you elaborate the issue!

**Comment by prashant2018** [comment]
@rrishabhj 
ya sure,
The enhancement required is to create a class which will allow developers in future using this library to implement or use recyclerview into their project in just few lines of code. 
Like if you read our readme file there you can see that SQLlite ,Shared Preferences and Animations are already implemented which allows developers to use these functionality in just 2-3 lines of code.

**Comment by SubhrajyotiSen** [comment]
I would like to take up this issue. 
Plus could you please mention what functionalities you want for the RecyclerView?

**Comment by prashant2018** [comment]
@SubhrajyotiSen Hi,
Functionalities:
1.A class to create a recyclerview in 2-4 lines
2.OnItemClickListener
Add more if you want :-)

Instructions:
1. goto : shortroid/src/main/java/shortroid/com/shortroid/
2. Create a package ShortRecyclerView with same class name.

**Comment by SubhrajyotiSen** [comment]
I can add swipe to dismiss too. But that will increase minAPI level to 11.
Any suggestons?
